/robot_news_station_bb8:
  ros__parameters:
    name: "bb8"

/robot_news_station_daneel:
  ros__parameters:
    name: "daneel"

/robot_news_station_jander:
  ros__parameters:
    name: "jander"

/robot_news_station_c3po:
  ros__parameters:
    name: "c3po"